### ISSUE TITLE
Failed to apply prefix

### ISSUE THREAD

**Issue by aaa707** [wbolster/emacs-direnv#13]
Hi there,
Thank you for the useful package.

But I have found a bug how to use pcase function. I guess it accepts back quote not quote. Also, it fails byte-compile too.

Here is the diff:

```diff
@@ -119,9 +119,9 @@ usually results in coloured output."
            (face)
            (prefix))
       (pcase state
-        ('added   (setq prefix "+" face 'diff-added))
-        ('changed (setq prefix "~" face 'diff-changed))
-        ('removed (setq prefix "-" face 'diff-removed)))
+        (`added   (setq prefix "+" face 'diff-added))
+        (`changed (setq prefix "~" face 'diff-changed))
+        (`removed (setq prefix "-" face 'diff-removed)))
       (propertize (concat prefix name) 'face face))
     (--sort
      (string-lessp (symbol-name (cdr it)) (symbol-name (cdr other)))
```

Thanks,

**Comment by wbolster** [comment]
can you tell me what exactly the bug is?

it seems to work fine, and https://www.gnu.org/software/emacs/manual/html_node/elisp/Pattern-matching-case-statement.html seems to indicate that symbols can be used with a normal (not backtick) quote.

also, i just tried to byte-compile using `M-x byte-compile-this-file` and i did not encounter any issues.

are you using a recent emacs version?

**Comment by aaa707** [comment]
I see.
My emacs version is

```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-11 on builder10-9.porkrind.org
```

I got an error like this when byte compiling:

```
direnv.el:114:1:Error: Unknown upattern `(quote added)'
```

But it's the old version, so I close this issue and try to update it.

**Comment by wbolster** [comment]
(to be clear: i'm not saying you're wrong, just that i cannot reproduce locally.)
