### ISSUE TITLE
Add direnv-executable-find

### ISSUE THREAD

**Issue by bkchr** [wbolster/emacs-direnv#15]
Hi, 
It would be nice if you could add a direnv-executable-find function. This function should wrap executable-find and should just setup the environment variables, based on the current working directory.

I have the idea for this function from nix-executable-find ([nix-emacs](https://github.com/travisbhartwell/nix-emacs)).

**Comment by wbolster** [comment]
hmmm. how is this better than `direnv-update-environment` followed by running the command normally?

the problem with finding just _one_ executable is that any executables spawned by that executable do _not_ have the right `PATH`, so in general it's an antipattern.

that said, `direnv exec` exists to solve this, but `emacs-direnv` does not have helpers for it (and i think it is out of scope since it is not related to emacs at all tbh.)

**Comment by bkchr** [comment]
Okay, maybe you need more context :D 
I used [lsp-rust](https://github.com/emacs-lsp/lsp-rust/blob/master/lsp-rust.el) and tried to modify the lsp-rust--rls-command function. The problem in this case is, that lsp-rust--rls-command is called while the major-mode (rust-mode) is loaded and at this time direnv was not called yet. I tried to call direnv-update-environment manually, but for some reason my $HOME path was not set correctly and in my .direnv file I used "PATH_add ~/.cargo/bin". 
The best would be that direnv could be called before running any major mode function, but I think that is not possible?

**Comment by wbolster** [comment]
if the command run by `lsp-rust` depends on the current project (for which direnv nicely can handle different environments based on the project's path) to run an executable, i think it should just call that executable instead of detecting a path at startup.

what if you had two rust projects open at the same time? `emacs-direnv` is _designed_ to switch between buffers and transparently make everything work. i use this for instance with python project to switch between virtual environments (`virtualenv`), which means that the path to tools like linters, but also the `python` executable itself, changes whenever i switch buffers (via `direnv-mode`).

**Comment by bkchr** [comment]
Hmm. I will need to think about that again, but I use Nixos and have different rust versions for different projects. The main problem is that tools like the rust language server are only findable in my setup in these project folders. So it would be the best that I could search for the rls executable when I switch into my project.

**Comment by wbolster** [comment]
fwiw, i also use tools that can only be found when is switch into a specific `direnv` controlled directory, e.g. linters and test runners. tools like `flycheck` will just execute `flake8` (python linter) and thanks to `emacs-direnv`, the right one is started.

**Comment by wbolster** [comment]
i see you closed this issue. let me know if there is anything that can be done to improve certain workflows.

i do not have definitive answers either. feel free to reopen in case you have ideas. :)

**Comment by bkchr** [comment]
Yeah, I was unsure. If I need more help or have better feedback, I will come back :)

**Comment by lassik** [comment]
Speaking from a lot of Emacs and Unix experience over many years and platforms, I think @wbolster made the right call here. In particular due to this:

> the problem with finding just _one_ executable is that any executables spawned by that executable do _not_ have the right `PATH`, so in general it's an antipattern.

Many Emacs packages have variables to specify a custom command name, but that tends to be a [leaky abstraction](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/). Life is much simpler when we arrange to have all our commands in PATH under their standard names, as direnv and emacs-direnv now do.
